### ISSUE TITLE
ansible-vault-helper gives unclear instructions

### ISSUE THREAD

**Issue by anttilaiti** [lvillani/ansible-tools#4]
If I checkout a project with already vaulted secrets to a new machine and try to provision:
```
$ ansible-playbook -i inventory/production machine.yml
Unable to find a password with name myvaultname.

Call myvaultname --set to save a password inside the keyring.
Unable to run ansible-vault-helper. Cannot continue.
```

However:
```
$ ansible-vault-helper myvaultname --set
usage: ansible-vault-helper [-h] [-u]
ansible-vault-helper: error: unrecognized arguments: jugu --set
```

At this point I am a bit confused, what binary should I call with`myvaultname --set` parameters?

Looks like `ansible-vault-helper -u` fixes the situation but I am unsure whether that is actually the right command here?

It also gives a warning about changing the vault PW – my first thought on that was that it would actually change the encryption PW of the secret and re-encrypt them. But it actually changes (or creates) the PW used to access the vaulted secret file(s) to MacOS keychain. This is a tad confusing as well.

My ansible.cfg has:
```
[vault]
name = myvaultname
```

**Comment by lvillani** [comment]
You are totally right, `ansible-vault-helper`'s interface is a bit of a mess right now. I'll try to fix it "soon" but I can't make promises as to when that'll happen at this time.

**Comment by lvillani** [comment]
Hi, I pushed a bunch of changes that _should_ improve the error message a bit. Can you try out what's currently in `master`? (Beware: `master` strictly requires Python >= 3.5, I might back-port these changes to the Python 2/3 version, I haven't decided yet).

**Comment by anttilaiti** [comment]
Sure thing! I'll give it a go.

**Comment by anttilaiti** [comment]
I checked `ansibletools` dir from master to `/usr/local/lib/python3.8/site-packages/ansibletools` and now it responds this way to ansible-vault command when vault pass is unset:

```
Unable to obtain password for vault "myvaultname" from the keyring.

Call "ansible-vault-helper --update" to add or update the vault's password
to the keyring.

Unable to run ansible-vault-helper. Cannot continue.
```

So in short; this issue seems to be fixed. Thanks!

**Comment by lvillani** [comment]
Glad it fixed the problem! I'll set a reminder to make an official release by the end of the week :)
